In [12]:
from cohlib.mvcn import gen_mvcn_params, sample_zs_from_Gamma
import numpy as np

test, freqs = gen_mvcn_params(0.01, 3)


In [15]:
np.round(test[0,:,:],3)
ccov = test[0,:,:]

In [26]:
def transform_cov_c2r(complex_cov):
    dim = complex_cov.shape[0]
    A = np.real(complex_cov)
    B = np.imag(complex_cov)
    rcov = np.zeros((2*dim, 2*dim))
    
    rcov = np.block([[A, -B],
                     [B, A]])

    return rcov/2

def transform_cov_r2c(real_cov):
    dimR = real_cov.shape[0]
    dimC = int(dimR/2)
    ccov = np.zeros((dimC, dimC), dtype=complex)

    Re = real_cov[:dimC,:dimC]
    Im = real_cov[dimC:,:dimC]

    ccov = 2*Re + 2*1j*Im

    return ccov

rcov = transform_cov_c2r(ccov)

In [27]:
np.round(ccov, 3)

array([[ 6.926+0.j   , -0.521+2.047j, -3.867+1.859j],
       [-0.521-2.047j,  2.963+0.j   , -0.621+0.314j],
       [-3.867-1.859j, -0.621-0.314j,  5.306+0.j   ]])

In [40]:
np.round(rcov, 3)

array([[ 3.463, -0.261, -1.934, -0.   , -1.023, -0.93 ],
       [-0.261,  1.482, -0.311,  1.023, -0.   , -0.157],
       [-1.934, -0.311,  2.653,  0.93 ,  0.157, -0.   ],
       [ 0.   ,  1.023,  0.93 ,  3.463, -0.261, -1.934],
       [-1.023,  0.   ,  0.157, -0.261,  1.482, -0.311],
       [-0.93 , -0.157,  0.   , -1.934, -0.311,  2.653]])

In [41]:
ccov_new = transform_cov_r2c(rcov)
np.round(ccov_new, 3)

array([[ 6.926+0.j   , -0.521+2.047j, -3.867+1.859j],
       [-0.521-2.047j,  2.963+0.j   , -0.621+0.314j],
       [-3.867-1.859j, -0.621-0.314j,  5.306+0.j   ]])

In [42]:
def get_conv_order_I(K, J):
    """
    Assume we have z = (z_1^1, ... z_1^K, z_2^1, ... z_2^K, ... z_J^1, ... z_J^K)
    Create matrix I that converts ordering of z to 
    z_new = (z_1^1, ..., z_J^1, z_1^2, ... z_J^2, ... z_1^K, ..., z_J^K)
    """
    # make sure we actually need this first (computationally)
    pass



In [ ]:
J = 100
K = 3

P_z = np.zeros((K*J, K*J))